- src/App.tsx
- src/styles/global.scss
- tailwind.config.js
* suit 폰트 tailwindcss에서 사용 가능하도록 classname설정
* 기본 색상 세팅
> [ chore ] 폰트, 색상 설정

- .dockerignore
- .github/workflows/ncp-deploy.yml
- Dockerfile
- package.json
* 네이버 클라우드 도커 이미지 자동 배포 깃 액션 추가
* 도커 이미지 파일 생성용 도커파일 작성
> 네이버 클라우드 자동배포 로직 추가

- .github/workflows/ncp-deploy.yml
- Dockerfile
- nginx.conf
> [ chore ] https관련 nginx 설정 추가

- nginx.conf
> [ chore ] 인증서 갱신용 설정 수정

- src/App.tsx
- src/components/layout/DefaultLayout.tsx
- src/constant/route.ts
- src/hooks/useEffectAfterMount.ts
- src/pages/signup/components/Terms.tsx
- src/pages/signup/index.tsx
- src/routes.tsx
- src/utils/location.ts
- 서비스 이용약관 페이지 퍼블리싱 완료된 부분 먼저 추가하였습니다.
- 헤더와 하단 바가 따로 필요한 경우가 있을 수 있어 둘을 useIsLayout를 분리하였습니다.
> 서비스 이용약관 페이지 추가

- src/components/buttons/toggle/ToggleButton.tsx
> [ feat ] 토글 버튼 컴포넌트 추가

- .github/workflows/auto-build.yml
> [ fix ] 깃 액션 오류 수정

- src/components/buttons/BottomButton.stories.tsx
- src/components/buttons/BottomButton.tsx
> 하단 버튼 컴포넌트 추가

- src/components/layout/BottomNavbar.tsx
- src/components/popup/Popup.stories.tsx
- src/components/popup/Popup.tsx
- src/components/popup/PopupGroup.tsx
- src/styles/global.scss
* 팝업 디자인 변경
* 스토리북 수정
* 폰트 스타일 추가 (popup title)
#38
> [ style ] 팝업 디자인 변경

- src/components/datepicker/Datepicker.stories.tsx
- src/components/datepicker/Datepicker.tsx
* 오늘 날짜 이전은 선택 불가능하도록 수정
* 선택날짜 기준으로 100일 이후는 선택 불가능하도록 수정
* 디자인 수정
close #45
> [ feat ] datepicker 기능 추가 및 스타일 변경

- index.html
- package-lock.json
- package.json
- src/App.tsx
- src/api/core.ts
- src/api/login.ts
- src/components/buttons/BottomButton.tsx
- src/components/buttons/SocialLoginButtons/KakaoLoginButton.tsx
- src/components/layout/DefaultLayout.tsx
- src/components/modal/BottomModal.stories.tsx
- src/components/modal/BottomModal.tsx
- src/constant/route.ts
- src/hooks/useLogin.ts
- src/main.tsx
- src/pages/agreement/components/Terms.tsx
- src/pages/agreement/index.tsx
- src/pages/login/LoginRedirect.tsx
- src/pages/login/index.tsx
- src/pages/profile/index.tsx
- src/pages/signup/components/Terms.tsx
- src/pages/signup/index.tsx
- src/recoil/user/atom.ts
- src/routes.tsx
- src/utils/cookie.ts
- 카카오 SDK 사용하여 인가 코드 가져와도록 수정
- 개발 서버 기본 포트 8080으로 수정
- 리액트 쿠키 사용하여 토큰 쿠키 관리
- 이용약관 페이지에서 리액트 노션으로 노션 페이지 임베딩
- axios 기본 설정
- useLogin hook 추가
- 로그인, 이용약관 페이지를 DefaultLayout으로 감싸지 않도록 수정.
- DefaultLayout에서 로그인, 약관 동의 여부 검사하여 로그인 되지 않은 경우 로그인, 이용약관 페이지 동의하지 않은 경우 동의 페이지로 강제 navigate하도록 수정
- 라우터: createBrowserRouter 이용하도록 수정
> 카카오 로그인 구현

- src/api/login.ts
- src/pages/login/LoginRedirect.tsx
- 로그인 api 호출시 환경에 따라 redirectUri 전송
> 로그인 api 호출시 환경에 따라 redirectUri 전송

- src/api/nottodo.ts
- src/components/banner/MainBanner.stories.tsx
- src/components/card/Card.tsx
- src/pages/nottodo/NotTodoCreatePage.tsx
- src/pages/nottodo/index.tsx
- src/recoil/nottodo/atom.ts
- src/utils/datepicker.ts
* 낫투두 리스트 api 작업 (CRUD)
* 날짜 형식 yyyymmdd -> yyyy-mm-dd 으로 변경
> 65 리스트 api 작업

- src/api/login.ts
- src/components/layout/DefaultLayout.tsx
- src/hooks/useLogin.ts
- src/hooks/useUserInfo.ts
- src/pages/agreement/components/Terms.tsx
- src/pages/agreement/index.tsx
- src/pages/profile/ProfileEditPage.tsx
- src/pages/profile/index.tsx
- src/recoil/user/atom.ts
- 사용자 닉네임 수정 
- 자동 로그인 여부 수정
- 회원 탈퇴
- 로그아웃
> 회원정보 페이지 API 적용

- src/api/nottodo.ts
- src/pages/nottodo/index.tsx
> [ fix ] 낫투두 리스트 수정

- src/api/core.ts
> [ merge into main ] 버그 수정

- src/App.tsx
- src/api/badge.ts
- src/pages/badge/components/BadgeList.tsx
- src/pages/badge/detail.tsx
- src/pages/badge/index.tsx
- src/routes.tsx
- src/utils/date.ts
* 뱃지 api 연결
* 이미지 url 시크릿 추가 ( 네이버 클라우드 주소 )
> [ feat ] 뱃지 api 연결

- src/components/datepicker/Datepicker.tsx
- src/pages/home/index.tsx
* datepicker 주간 월간 모드 변경 시 날짜 버그 수정
> [ fix ] datepicker 버그 수정

- src/components/banner/MainBanner.tsx
- src/pages/home/index.tsx
- src/pages/nottodo/NotTodoCreatePage.tsx
- src/utils/datepicker.ts
* 타이틀 노출 안되던 문제 수정 ( 목표와 타이틀이 바뀌어 있었음 )
* 목표 정해달라는 문구 띄울땐 클릭 시 수정페이지로 이동
> 홈 탭 낫투두 타이틀 미노출 및 텍스트 스타일 변경

- src/pages/home/components/moderationList.tsx
> [ fix ] 텍스트 길이 수정

- src/pages/home/index.tsx
> [ fix ] 절제기록 4자 버그 수정

- src/pages/nottodo/NotTodoCreatePage.tsx
> [ fix ] 수정된게 없으면 버튼 비활성화

- src/pages/nottodo/index.tsx
> [ fix ] 종료 낫투두 수정 불가

- src/components/card/Card.tsx
- src/components/common/input/Input.tsx
- src/components/layout/DefaultLayout.tsx
- src/constant/route.ts
- src/pages/nottodo/NotTodoCreatePage.tsx
- src/pages/nottodo/index.tsx
- src/utils/location.ts
* 종료된 낫투두는 클릭 시 디테일 페이지로 이동 ( 수정 불가능 )
> [ fix ] 종료된 낫투두는 누르면 디테일 페이지로 이동

- src/pages/nottodo/index.tsx
> [ fix ] card 컴포넌트 key값 변경

- src/pages/nottodo/index.tsx
> [ fix ] 진행 예정 낫투두 수정 페이지 이동
